### ISSUE TITLE
mainbot/module: Stage Management

### ISSUE THREAD

**Issue by rekitchb** [CoffeeBreak-Discord/roadmap#2]
## Summary
This module provide some feature that helping podcast admin to auto-invite user to Stage.

## Target
- [x] Speaker auto invite for Stage
- [x] Auto Give Role for user when entering stage
- [ ] TBA

## To do list
- [ ] TBA

**Comment by ikr4-m** [comment]
This module will improve when the "Event Universe" module is done.
